### PR TITLE
Bootstrap 3 theme

### PR DESCRIPTION
**Pull request by cmengler**

### CODE REVIEW

**Comment by erickok** [comment]
Neat! Do you have a publically available example or a screenshot?

**Comment by firebirdberlin** [comment]
Adding indentation to the output files is an incompatible change which should be clearly communicated. The custom settings have to be updated when switching to this version. Nevertheless I recommend to go this step because translation files are indented by Android Studio by default.

**Comment by cmengler** [comment]
@erickok I've created an example site -- https://cmengler.com/pastt/ -- I'm working on a tweak to the table responsiveness with long strings. My thought is to stack the key, string, and input field in this scenario. Will update PR shortly :)

**Comment by cmengler** [comment]
@firebirdberlin I agree too, I realised this after I had did my initial commit. I'll revert this change from this PR and create a new PR for the indention change. :)

**Comment by erickok** [comment]
It looks neat, I like it. Thanks!

**Pull request merged**
